### ISSUE TITLE
[Suggestion] Use light favicon for dark theme

### ISSUE THREAD

**Issue by raunofreiberg** [modulz/modulz-website#53]
Hey 👋

While passing by, I noticed that the favicon of Modulz is not very noticeable on a dark theme. 

![image](https://user-images.githubusercontent.com/23662329/80235956-0f039a00-8663-11ea-85b1-3ad7d2da204f.png)

I think a lighter favicon would look nicer and should be fairly trivial to implement with something like this: 🙂

```html
<link rel="icon" media="(prefers-color-scheme: dark)" href=""/>
<link rel="icon" media="(prefers-color-scheme: light)" href="" />
``` 

Keep up the good work!

**Comment by peduarte** [comment]
That's a great idea. I'll give it a go, thank you!

**Comment by peduarte** [comment]
Tried that but I couldnt get it to work properly. I think there's a difference between the OS light/dark theme and a Chrome theme?

**Comment by raunofreiberg** [comment]
Hmm... It could be that the `media` attribute does not work.

You could do this instead:

```jsx
const isDarkMode = typeof window !== 'undefined' && 
window.matchMedia && window.matchMedia('(prefers-color-scheme: dark)').matches;

<link
  rel="shortcut icon"
  href={isDarkMode ? '/static/favicon-light.ico' : '/static/favicon-dark.ico'}
/>
```
